### ISSUE TITLE
Settings button crashes MuseScore on Ventura

### ISSUE THREAD

**Issue by Fosterclark** [TrebledJ/musescore-todo-list#1]
Otherwise seems to work
some detail how to use would be good.
thanks

**Comment by TrebledJ** [comment]
Hey, thanks for the feedback. I've added usage guidelines on the [readme](https://github.com/TrebledJ/musescore-todo-list#usage) and the MS plugin page.

I'm not using Ventura, so can't reproduce the crash issue immediately. Can you let me know...
1. What MuseScore version are you using?
2. Are there any logs from the crash? If yes, you can upload it as a [gist](https://gist.github.com/) and link it here.

**Comment by Fosterclark** [comment]
1.Musescore 4.11 latest.
2. Sorry

**Comment by TrebledJ** [comment]
Ah cool, the v4.0 QML file uploaded on the MS plugin page was made by another contributor and I haven't tested it on MS4 yet. I'll have to look at the plugin development ecosystem for MS4 (as I heard it will only be ready by v4.2? not sure). Will get back to you.

**Comment by TrebledJ** [comment]
Hi, I've tested with Monterey and uploaded a new version. You can get it in either link:

- https://musescore.org/en/project/musescore-do-list
- https://github.com/TrebledJ/musescore-todo-list/releases/tag/v4.0.0

It shouldn't crash when you open settings now. (See the [MS4 note](https://github.com/TrebledJ/musescore-todo-list/#musescore-4) for more info.) Let me know if it works (or doesn't work) for you.

**Comment by Fosterclark** [comment]
Works great
Thanks
